### ISSUE TITLE
Receiving this error in Rspec when I begin the lab

### ISSUE THREAD

**Issue by jamesnvk** [learn-co-curriculum/rails-create-action-lab#4]
DEPRECATION WARNING: You didn't set `secret_key_base`. Read the upgrade documentation to learn more about this new config option. (called from load at /Users/james/.rvm/gems/ruby-2.2.1/bin/rspec:23)

  An error occurred in an after hook
    NoMethodError: undefined method `original_path_set' for nil:NilClass
    occurred at /Users/james/.rvm/gems/ruby-2.2.1/gems/rspec-rails-3.0.2/lib/rspec/rails/view_rendering.rb:98:in `block (2 levels) in <module:ViewRendering>'

  An error occurred in an after hook
    NoMethodError: undefined method `each' for nil:NilClass
    occurred at /Users/james/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.3/lib/action_controller/test_case.rb:58:in `teardown_subscriptions'

F

Failures:

  1) StudentsController POST create with valid attributes creates a new student
     Failure/Error: Unable to find matching line from backtrace
     RuntimeError:
       Missing `secret_token` and `secret_key_base` for 'test' environment, set these values in `config/secrets.yml`
     # /Users/james/.rvm/gems/ruby-2.2.1/gems/railties-4.2.3/lib/rails/application.rb:534:in `validate_secret_key_config!'
     # /Users/james/.rvm/gems/ruby-2.2.1/gems/railties-4.2.3/lib/rails/application.rb:246:in `env_config'
     # /Users/james/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.3/lib/action_dispatch/testing/test_request.rb:17:in `initialize'
     # /Users/james/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.3/lib/action_controller/test_case.rb:200:in `initialize'
     # /Users/james/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.3/lib/action_dispatch/testing/test_request.rb:13:in `new'
     # /Users/james/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.3/lib/action_dispatch/testing/test_request.rb:13:in `new'
     # /Users/james/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.3/lib/action_controller/test_case.rb:679:in `build_request'
     # /Users/james/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.3/lib/action_controller/test_case.rb:668:in `setup_controller_request_and_response'
     # /Users/james/.rvm/gems/ruby-2.2.1/gems/rspec-rails-3.0.2/lib/rspec/rails/adapters.rb:111:in `block (2 levels) in setup'
     # /Users/james/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:294:in `instance_exec'
     # /Users/james/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:294:in `instance_exec'
     # /Users/james/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.0.4/lib/rspec/core/hooks.rb:349:in `run'
     # /Users/james/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.0.4/lib/rspec/core/hooks.rb:410:in `block in run'
     # /Users/james/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.0.4/lib/rspec/core/hooks.rb:410:in `each'
     # /Users/james/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.0.4/lib/rspec/core/hooks.rb:410:in `run'
     # /Users/james/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.0.4/lib/rspec/core/hooks.rb:485:in `run'
     # /Users/james/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:340:in `run_before_example'
     # /Users/james/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:147:in `block in run'
     # /Users/james/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:210:in `call'
     # /Users/james/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:210:in `block (2 levels) in <class:Procsy>'
     # /Users/james/.rvm/gems/ruby-2.2.1/gems/rspec-rails-3.0.2/lib/rspec/rails/example/controller_example_group.rb:174:in `block (2 levels) in <module:ControllerExampleGroup>'
     # /Users/james/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:294:in `instance_exec'
     # /Users/james/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:294:in `instance_exec'
     # /Users/james/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.0.4/lib/rspec/core/hooks.rb:430:in `block (2 levels) in run'
     # /Users/james/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:210:in `call'
     # /Users/james/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:210:in `block (2 levels) in <class:Procsy>'
     # /Users/james/.rvm/gems/ruby-2.2.1/gems/rspec-rails-3.0.2/lib/rspec/rails/adapters.rb:72:in `block (2 levels) in <module:MinitestLifecycleAdapter>'
     # /Users/james/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:294:in `instance_exec'
     # /Users/james/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:294:in `instance_exec'
     # /Users/james/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.0.4/lib/rspec/core/hooks.rb:430:in `block (2 levels) in run'
     # /Users/james/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:210:in `call'
     # /Users/james/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:210:in `block (2 levels) in <class:Procsy>'
     # /Users/james/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.0.4/lib/rspec/core/hooks.rb:432:in `run'
     # /Users/james/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.0.4/lib/rspec/core/hooks.rb:485:in `run'
     # /Users/james/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:303:in `with_around_example_hooks'
     # /Users/james/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.0.4/lib/rspec/core/example.rb:145:in `run'
     # /Users/james/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.0.4/lib/rspec/core/example_group.rb:494:in `block in run_examples'
     # /Users/james/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.0.4/lib/rspec/core/example_group.rb:490:in `map'
     # /Users/james/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.0.4/lib/rspec/core/example_group.rb:490:in `run_examples'
     # /Users/james/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.0.4/lib/rspec/core/example_group.rb:457:in `run'
     # /Users/james/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.0.4/lib/rspec/core/example_group.rb:458:in `block in run'
     # /Users/james/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.0.4/lib/rspec/core/example_group.rb:458:in `map'
     # /Users/james/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.0.4/lib/rspec/core/example_group.rb:458:in `run'
     # /Users/james/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.0.4/lib/rspec/core/example_group.rb:458:in `block in run'
     # /Users/james/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.0.4/lib/rspec/core/example_group.rb:458:in `map'
     # /Users/james/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.0.4/lib/rspec/core/example_group.rb:458:in `run'
     # /Users/james/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:112:in `block (2 levels) in run_specs'
     # /Users/james/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:112:in `map'
     # /Users/james/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:112:in `block in run_specs'
     # /Users/james/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.0.4/lib/rspec/core/reporter.rb:54:in `report'
     # /Users/james/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:108:in `run_specs'
     # /Users/james/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:86:in `run'
     # /Users/james/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:70:in `run'
     # /Users/james/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:38:in `invoke'
     # /Users/james/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.0.4/exe/rspec:4:in `<top (required)>'
     # /Users/james/.rvm/gems/ruby-2.2.1/bin/rspec:23:in `load'
     # /Users/james/.rvm/gems/ruby-2.2.1/bin/rspec:23:in `<main>'
     # /Users/james/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
     # /Users/james/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
     # 
     #   Showing full backtrace because every line was filtered out.
     #   See docs for RSpec::Configuration#backtrace_exclusion_patterns and
     #   RSpec::Configuration#backtrace_inclusion_patterns for more information.

Finished in 0.06258 seconds (files took 2.08 seconds to load)
1 example, 1 failure

**Comment by pletcher** [comment]
Looking at your solution, it seems like you figured out what was wrong -- good work!

And it looks like someone already added a secrets.yml to this repo, so I'm going to close this.
