### ISSUE TITLE
getting : Web Console is activated in the test environment, which is usually a mistake.

### ISSUE THREAD

**Issue by nicolefederici** [learn-co-curriculum/rails-create-action-lab#9]
I got this:

To ensure it's only activated in development
mode, move it to the development group of your Gemfile:

    gem 'web-console', group: :development

So I did that, and it seemed to fix that issue after bundle update. Then, there were other issues.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙
